apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: credential-manager
build:
  artifacts:
  - image: credential-manager
    context: code
    sync:
      manual:
      - src: 'code/*'
        dest: /project/*
deploy:
  kubectl:
    manifests:
      - ./k8s/*
portForward:
  - resourceType: service
    resourceName: credential-manager
    port: 6000
    address: 0.0.0.0
    localPort: 6000
