apiVersion: v1
kind: Service
metadata:
  name: credential-manager-service
spec:
  type: NodePort
  selector:
    app: credential-manager
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007
