apiVersion: v1
kind: Service
metadata:
  name: credential-manager-service
spec:
  type: NodePort
  selector:
    app: credential-manager
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
      nodePort: 30007
